/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CwcTestComponent {
    'open': () => Promise<void>;
    'opened': boolean;
    'title': string;
  }
  interface CwcTooltipClick {
    'text': string;
  }
}

declare global {


  interface HTMLCwcTestComponentElement extends Components.CwcTestComponent, HTMLStencilElement {}
  var HTMLCwcTestComponentElement: {
    prototype: HTMLCwcTestComponentElement;
    new (): HTMLCwcTestComponentElement;
  };

  interface HTMLCwcTooltipClickElement extends Components.CwcTooltipClick, HTMLStencilElement {}
  var HTMLCwcTooltipClickElement: {
    prototype: HTMLCwcTooltipClickElement;
    new (): HTMLCwcTooltipClickElement;
  };
  interface HTMLElementTagNameMap {
    'cwc-test-component': HTMLCwcTestComponentElement;
    'cwc-tooltip-click': HTMLCwcTooltipClickElement;
  }
}

declare namespace LocalJSX {
  interface CwcTestComponent extends JSXBase.HTMLAttributes<HTMLCwcTestComponentElement> {
    'opened'?: boolean;
    'title'?: string;
  }
  interface CwcTooltipClick extends JSXBase.HTMLAttributes<HTMLCwcTooltipClickElement> {
    'text'?: string;
  }

  interface IntrinsicElements {
    'cwc-test-component': CwcTestComponent;
    'cwc-tooltip-click': CwcTooltipClick;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


