/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CwcDigitalClock {}
  interface CwcPophover {}
  interface CwcProgressBar {
    'basecolor': string;
    'fillcolor': string;
    'fillprecent': number;
  }
  interface CwcTestComponent {
    'open': () => Promise<void>;
    'opened': boolean;
    'title': string;
  }
  interface CwcTooltipClick {
    'text': string;
  }
}

declare global {


  interface HTMLCwcDigitalClockElement extends Components.CwcDigitalClock, HTMLStencilElement {}
  var HTMLCwcDigitalClockElement: {
    prototype: HTMLCwcDigitalClockElement;
    new (): HTMLCwcDigitalClockElement;
  };

  interface HTMLCwcPophoverElement extends Components.CwcPophover, HTMLStencilElement {}
  var HTMLCwcPophoverElement: {
    prototype: HTMLCwcPophoverElement;
    new (): HTMLCwcPophoverElement;
  };

  interface HTMLCwcProgressBarElement extends Components.CwcProgressBar, HTMLStencilElement {}
  var HTMLCwcProgressBarElement: {
    prototype: HTMLCwcProgressBarElement;
    new (): HTMLCwcProgressBarElement;
  };

  interface HTMLCwcTestComponentElement extends Components.CwcTestComponent, HTMLStencilElement {}
  var HTMLCwcTestComponentElement: {
    prototype: HTMLCwcTestComponentElement;
    new (): HTMLCwcTestComponentElement;
  };

  interface HTMLCwcTooltipClickElement extends Components.CwcTooltipClick, HTMLStencilElement {}
  var HTMLCwcTooltipClickElement: {
    prototype: HTMLCwcTooltipClickElement;
    new (): HTMLCwcTooltipClickElement;
  };
  interface HTMLElementTagNameMap {
    'cwc-digital-clock': HTMLCwcDigitalClockElement;
    'cwc-pophover': HTMLCwcPophoverElement;
    'cwc-progress-bar': HTMLCwcProgressBarElement;
    'cwc-test-component': HTMLCwcTestComponentElement;
    'cwc-tooltip-click': HTMLCwcTooltipClickElement;
  }
}

declare namespace LocalJSX {
  interface CwcDigitalClock extends JSXBase.HTMLAttributes<HTMLCwcDigitalClockElement> {}
  interface CwcPophover extends JSXBase.HTMLAttributes<HTMLCwcPophoverElement> {}
  interface CwcProgressBar extends JSXBase.HTMLAttributes<HTMLCwcProgressBarElement> {
    'basecolor'?: string;
    'fillcolor'?: string;
    'fillprecent'?: number;
  }
  interface CwcTestComponent extends JSXBase.HTMLAttributes<HTMLCwcTestComponentElement> {
    'opened'?: boolean;
    'title'?: string;
  }
  interface CwcTooltipClick extends JSXBase.HTMLAttributes<HTMLCwcTooltipClickElement> {
    'text'?: string;
  }

  interface IntrinsicElements {
    'cwc-digital-clock': CwcDigitalClock;
    'cwc-pophover': CwcPophover;
    'cwc-progress-bar': CwcProgressBar;
    'cwc-test-component': CwcTestComponent;
    'cwc-tooltip-click': CwcTooltipClick;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


